fix TES compiling error.
(Assuming there is no error in driver.)

Fix error 1.

0(12) : error C7011: implicit cast from "int" to "float"
0(13) : error C7011: implicit cast from "int" to "float"

Fix error 2.

(0) : error C7548: 'tessellation evaluation shader' requires "#extension
GL_EXT_tessellation_shader : enable" before use
(0) : error C7548: 'tessellation evaluation shader' requires "#extension
GL_OES_tessellation_shader : enable" before use